version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
  crypto:
    image: crypto-levi9
    container_name: crypto-levi9
    ports:
      - 8080:8080
    links:
      - mongodb
